### ISSUE TITLE
Loggin in

### ISSUE THREAD

**Issue by mink4sure** [mink4sure/DjangoSimpleSite#2]
How to see if a user is logged in? There is a data base which checks whether the name corresponds the the password but how to remember?

**Comment by JWMvanLeeuwen** [comment]
Can't you give people an online status when logging in:
if(password corresponds to username):
continue to site
status='online'
else:
error wrong password

And then display the names if status =='online'

**Comment by mink4sure** [comment]
Yes, pherhaps. Good Idea!
Question is where this "status" is stored: The User database used is provided by Django, not sure whether they have a 'column' for this in the db.

And something else, say the user would forget to click on logout before he closes his browser, how then to update his status to 'offline' (or more likely False)

**Comment by JWMvanLeeuwen** [comment]
Perhaps you could set up a timer that gives a pop-up after a certain amount of time of non page reloading. The pop up could have a simple, yes im here button which would reset the timer or after a minute it changes your status to offline.
Now im gonna eat laterzz

**Comment by mink4sure** [comment]
Solution: Cookies.
https://django-book.readthedocs.io/en/latest/chapter14.html
